require("config.plugins-setup") 
require("config.core.options")
require("config.core.keymaps")
require("config.core.colorscheme")
require("config.plugins.comment")
require("config.plugins.lualine")
require("config.plugins.nvim-cmp")
require("config.plugins.lsp.mason")
require("config.plugins.lsp.lspconfig")
-- require("config.plugins.nvim-tree")
